### ISSUE TITLE
Zoom hotkeys

### ISSUE THREAD

**Issue by 153** [iccanobif/gikopoi2#300] opened 2021-06-13 22:43 UTC
`["-", "_"]` should zoom out, and `["=", "+"]` should zoom in. The reason why I include `_` and `=` is because I don't want to hold the shift key to zoom in, so we should treat the keys as zoom keys independent of modifier

**Comment by iccanobif** [comment] 2021-06-14 07:11
duplicate of https://github.com/iccanobif/gikopoi2/issues/171

**Closed** 2021-06-14 19:32 UTC
